 <!-- Plugins -->
    <script src="{{ asset('frontend/assets/js/vendor/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/jquery-3.7.1.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/jquery-ui.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/aos.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/smoothscroll.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/jquery.fancybox.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/slick.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/owl.carousel.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/swiper-bundle.min.js')}}"></script>
    <script src="{{ asset('frontend/assets/js/vendor/menu.js')}}"></script>
    <!-- main-js -->
    <script src="{{ asset('frontend/assets/js/main.js')}}"></script>